name: UMLS_regions_10k_short_prompt
neptune_logging: True
data_path: data/UMLS_regions_10k/short_prompt  # It looks for a train.json and test.json in the folder  
model_name: bert-large-uncased
batch_size: 16
num_epochs: 20
max_len: 512
train_ratio: 0.9 # 0.8 is 20k out of 25k
reduce_lines_for_testing: false # uses only 100 sentences to train model
lr: 0.000001
mislabel_percent: 0  # 0 if you don't want mislabeled data in the train set (not in val or test) 1 -> 1%, 2 -> 2% so on