name: DNeurOn
channels:
  - defaults
dependencies:
  - python=3.9
  - pyyaml
  - tqdm
  - networkx
  - graphviz
  - pygraphviz
  - scikit-learn
  - bokeh
  - matplotlib=3.5.1
  - plotly
  - colorcet
  - pip
  - pip:
    - neptune
    - torch>=2.0.1
    - transformers>=4.31.0
    - accelerate
    - optimum
    - auto-gptq
    - peft
    - fire
    - python-dotenv
    - openai