name: Large BERT smart training
neptune_logging: True
data_path: /home/projects/DeepNeurOntology/IMDB_data/
model_name: bert-large-uncased
batch_size: 16
num_epochs: 50
max_len: 512
train_lines: 20000 # out of 25k