name: yaml_test_run
neptune_logging: True
data_path: /home/projects/DeepNeurOntology/IMDB_data/
model_name: bert-large-uncased
embed_dim: 1024
batch_size: 
  - 512
  - 1024
num_epochs: 1
lr: 0.001
max_len: 128