name: test
neptune_logging: True
train_fpath: /home/projects/DeepNeurOntology/IMDB_data/train.json
dev_fpath: null #/home/projects/DeepNeurOntology/IMDB_data/train.json
test_fpath: null #/home/projects/DeepNeurOntology/IMDB_data/test.json 
model_name: bert-large-uncased
batch_size: 16
num_epochs: 12
max_len: 512
train_ratio: 0.8 # 0.8 is 20k out of 25k
reduce_lines_for_testing: true # uses only 100 sentences to train model
lr: 0.000001
mislabel_percent: 5  # 0 if you don't want mislabeled data in the train set (not in val or test) 1 -> 1%, 2 -> 2% so on
model_save_location: /home/projects/DeepNeurOntology/saved_models/ # /home/projects/DeepNeurOntology/saved_models/