name: test
neptune_logging: True
data_path: /home/projects/DeepNeurOntology/IMDB_data/
model_name: bert-large-uncased
batch_size: 16
num_epochs: 500
max_len: 512
train_ratio: 0.8 # 0.8 is 20k out of 25k
reduce_lines_for_testing: false # uses only 100 sentences to train model
lr: 0.000001