name: UMLS_regions_10k_quicktest
name_fields: !!python/tuple [model_name]
neptune_logging: True
train_fpath: data/UMLS_regions_10k/short_prompt/train.json
dev_fpath: null
test_fpath: data/UMLS_regions_10k/short_prompt/test.json
model_name: bert-large-uncased
batch_size: 16
num_epochs: 5
max_len: 512
model_save_location: null
reduce_lines_for_testing: true # uses only 100 sentences to train model
lr: 0.000001
mislabel_percent: 0  # 0 if you don't want mislabeled data in the train set (not in val or test) 1 -> 1%, 2 -> 2% so on